name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Change this to self-hosted EC2 runner label

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: NODE_OPTIONS="--max-old-space-size=512" npm ci 


    - name: Build with limited memory
      run: NODE_OPTIONS="--max-old-space-size=512" npm run build --if-present

